- name: openconnect | ensure Ansible PPA pre-requisites are met
  apt: pkg=python-pycurl state=installed

# I need this in some rare instances
- name: openconnect | add PPA for open connect
  apt_repository: repo='ppa:mtmiller/openconnect'

- name: openconnect | install Cisco Open Connect
  apt: pkg=openconnect state=installed
